name=Adafruit AS7331 Library
version=1.0.1
author=Adafruit
maintainer=Adafruit <info@adafruit.com>
sentence=Arduino library for the AS7331 UV spectral sensor.
paragraph=Supports UVA, UVB, UVC measurements with gain, integration time, and irradiance conversion.
category=Sensors
url=https://github.com/adafruit/Adafruit_AS7331
architectures=*
depends=Adafruit BusIO
